gwcat0506/DBP_Project

prisma/schema.prisma
=> prisma DB연결

prisma/schema.prisma
closed #3 
모델 생성 및 데이터 적재하였습니다.
=> [feat] create db

app.js, nodemon.json, src/controller/index.js, src/controller/projectController.js, src/router/index.js, src/router/projectRouter.js, src/service/index.js, src/service/projectService.js
Resolved #5 
프로젝트 검색 기능 구현하였습니다.
=> [feat] 프로젝트 검색 구현

src/controller/projectController.js, src/router/projectRouter.js, src/service/projectService.js
Resolved #12 
프로젝트 상세 조회 기능 구현하였습니다.
=> [feat] 프로젝트 상세 조회 구현

src/public/main.html, src/service/projectService.js
Resolved #23 
- 프론트에서 날짜 필터 활용하여 검색 가능하도록 수정하였습니다.
- 날짜 필터로 검색 시 착수일과 종료일 사이의 프로젝트가 조회되도록 수정하였습니다.
=> [Fix] 프로젝트 검색 수정

src/controller/projectController.js, src/service/projectService.js
- 프로젝트 기간 설정 시 종료 날짜가 null인 경우 포함
- 프로젝트 종료 날짜가 null일 경우 '진행중' 표시
=> [Fix] 프로젝트 검색 날짜 필터 수정

src/controller/projectController.js, src/router/projectRouter.js, src/service/projectService.js
=> [Feat] 프로젝트 직원 투입 구현

src/controller/projectController.js, src/router/projectRouter.js, src/service/projectService.js
=> [Feat] 직원 경력 및 기술 검색

src/controller/projectController.js, src/router/projectRouter.js, src/service/projectService.js
=> [Feat] 직원 평균 평가점수 검색 구현

.gitignore, src/public/main.html
=> [Fix] gitignore 파일 수정

src/controller/projectController.js, src/router/projectRouter.js, src/service/projectService.js
=> [Feat] 평가 조회 구현

src/controller/employeeController.js, src/router/employeeRouter.js, src/service/employeeService.js
=> [Feat] 사원 정보 수정

src/public/css/mypage.css, src/public/login.html, src/router/mypageRouter.js
=> [Feat] 로그인 비밀번호 보이기 구현

app.js, src/public/SignUp.html, src/public/login.html, src/public/main.html, src/public/pj_push.html, src/router/employeeRouter.js, src/service/employeeService.js
=> [Fix] 직원 검색, 갱신 수정 및 라우팅 경로 변경

src/service/employeeService.js
Resolved #56 
- 주민등록번호를 생년월일로 전송합니다.
=> [Fix] 사원 검색 응답값 수정

src/public/employee.html
=> 직원 조회 버튼 생성

src/public/pj_push.html
=> [Feat]프로젝트 추가 - 직무검색 구현

app.js, package-lock.json, package.json, prisma/schema.prisma, src/controller/authController.js, src/controller/index.js, src/controller/userController.js, src/public/login.html, src/public/mypage.html, src/router/index.js, src/router/userRouter.js, src/service/index.js, src/service/userService.js, yarn.lock
=> [Feat] 내 정보 조회 구현

src/controller/userController.js, src/router/userRouter.js, src/service/userService.js
=> [Feat] 비밀번호 변경 구현

src/public/employee.html, src/public/projectinquiry.html
=> 직원 정보 갱신 페이지 연결

src/public/pj_push.html, src/public/projectcreate.html, src/public/projectinquiry.html, src/service/projectService.js
=> [Feat] 프로젝트 상세 보기 구현

src/controller/projectController.js, src/public/main.html, src/public/pj_push.html, src/public/projectcreate.html, src/public/projectinquiry.html
=> [Feat]프로젝트 별 더보기 구현

src/public/main.html
=> [Fix] 프로젝트 조회 default값 설정

src/public/projectcreate.html
=> [Fix]프로젝트 상세보기 수정

src/public/emp_info.html, src/public/employee.html, src/public/projectcreate.html, src/public/projectinquiry.html
=> [Feat] 직원 더보기 구현

src/public/project_eval.html, src/public/projectinquiry.html, src/service/employeeService.js
=> [Fix]직원 더보기 구현

src/service/projectService.js
=> [Fix] 프로젝트 상세 조회 이슈 해결

src/controller/employeeController.js, src/public/emp_info.html, src/public/projectcreate.html, src/public/projectinquiry.html
=> [Fix] 프로젝트 상세 조회 이슈 프론트 반영

src/public/project_eval.html, src/public/projectinquiry.html
=> [Feat] 프로젝트 평가 조회 구현

src/public/css/project_eval.css, src/public/mypage.html, src/public/project_eval.html
마이페이지
- 비밀번호 안보이게 수정.
평가조회 페이지
- pm, 고객, 동료 평가 제목 글씨 키우고 bold처리
- data 나오는 부분 바탕 흰색으로 처리
=> 마이 페이지, 평가조회 페이지 수정

src/public/projectinquiry.html, src/service/projectService.js
시작일 / 마감일 합치고 종료일 새로 생성
설명란 앞으로 땡겨서 다른 table과 조정하였음.
=> 프로젝트 상세 페이지 수정

src/controller/projectController.js, src/public/login.html, src/public/mypage.html, src/public/projectcreate.html, src/public/projectinquiry.html, src/service/projectService.js
프로젝트 생성시 프로젝트 상세 보기에 프로젝트 id가 안 뜨던 문제 해결
=> [Fix] 프로젝트 상세 보기 이슈 해결

src/public/project_eval.html
=> [Fix] 평가보기 title에 직무 추가

src/controller/userController.js, src/public/projectinquiry.html, src/public/roadmap.html, src/service/userService.js
=> [Feat] 투입 종료 날짜 추가

src/public/mypage.html
=> [Fix] 마이페이지 수정

src/public/mypage.html, src/public/projectinquiry.html
=> [Feat] 프로젝트 상세 보기 직원 수 구현
